@extend("Masters\\master-no-jumbotron.razr.php")

@block('contentblock')
<section id="terms-of-use">
    <h1>Terms of Use</h1>
    <p><span>Last Updated: March 18, 2016</span></p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras dui elit, dictum sit amet gravida ut, porta nec nibh. Aliquam vel rhoncus arcu. Phasellus interdum magna non tortor tempor posuere. Morbi vitae vehicula felis. Donec porta sem laoreet, ultricies neque ut, viverra augue. Aenean arcu ipsum, sagittis sit amet consectetur in, vestibulum mattis sapien. Curabitur nec augue ut ex pharetra scelerisque.</p>
    <p>Etiam id eros risus. Quisque posuere euismod nisl quis fermentum. Aliquam erat volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sollicitudin pulvinar diam id molestie. Suspendisse at bibendum ex. Praesent eros orci, laoreet in eleifend sed, elementum quis quam. Cras nec dui purus. Aliquam id ultrices sem. Etiam rhoncus accumsan bibendum. Nulla eu dictum velit, nec congue justo. Fusce consectetur purus nec varius mollis. In eu condimentum sem. Quisque porta odio eu elementum convallis. Vestibulum a viverra est, sit amet blandit nisl. Etiam vel eros tempus nunc mollis egestas. Vestibulum viverra mollis massa, vel maximus nisi mollis eget. Maecenas sodales gravida nisl, ut semper lacus fringilla a. Nam nec aliquet nisl, id dapibus urna. Praesent posuere consectetur leo, vitae facilisis augue sodales lacinia. Phasellus nunc sapien, ultricies sed volutpat ac, aliquam at libero. Morbi lacinia turpis sit amet justo ullamcorper consectetur. Vivamus eu augue neque. Praesent consequat tempus molestie. Donec porta pretium sem, in dapibus lacus porta vitae. Proin eleifend libero sit amet luctus fermentum. Pellentesque augue ante, cursus quis augue ac, posuere laoreet sapien. Morbi tincidunt molestie nunc, in luctus lorem.</p>
    <h2></h2>
    <p>Sed tincidunt et massa sit amet convallis. Nunc magna tortor, iaculis ac elit vel, pellentesque tempus dolor. Vivamus lorem tortor, tincidunt in turpis sit amet, accumsan facilisis lacus. Integer dictum aliquet turpis, eu porta lectus dapibus sit amet. Sed convallis, nisl vel suscipit imperdiet, nulla dui porta leo, at suscipit justo massa blandit felis. Sed semper risus ut dignissim lobortis. Donec a aliquam tellus. Donec ut condimentum arcu. Ut vel tempus mi, nec convallis ex. Integer non auctor tortor, nec tempor turpis. Suspendisse congue velit ultrices, consectetur ex dignissim, rhoncus mauris. Aliquam a semper lectus. Duis leo erat, vulputate et nibh in, imperdiet luctus ligula.</p>
    <p>Duis eget nisi ut erat viverra tristique. Fusce eget imperdiet velit, in luctus dolor. Proin non enim tempor elit finibus sollicitudin et sed arcu. Suspendisse volutpat, massa et auctor malesuada, turpis neque eleifend eros, non ultrices libero enim a dui. In molestie turpis sit amet mollis aliquet. Fusce vel sodales erat, ut porta sem. Aenean venenatis ut ante tristique finibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
    <p>Vivamus sed condimentum orci. Phasellus condimentum malesuada felis, non facilisis nulla varius at. Morbi ultrices justo pulvinar, fringilla metus ut, vulputate dui. In non congue velit. Quisque vitae nisi et arcu tincidunt tempus ut non lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum facilisis leo nec mi sagittis, non accumsan risus molestie. Nullam auctor euismod magna sit amet ultrices. Nulla vel dictum mi, ac luctus ex.</p>
    <p>Aenean luctus ligula hendrerit, imperdiet turpis quis, congue ante. Nullam sagittis eget dui in maximus. Donec a varius neque, a vehicula ex. Nam pharetra enim sit amet nulla faucibus tincidunt nec quis lacus. Aliquam id fringilla ante. Aenean sed justo et nibh aliquam pellentesque quis at justo. Nam tempus nisl nec egestas gravida. Praesent et nisi neque. Quisque id ligula et magna condimentum rhoncus interdum ut ex. Pellentesque tristique, nibh id auctor sodales, massa leo tempor sapien, id placerat risus mi sed dolor. Donec in mauris suscipit, ornare lectus vel, imperdiet sapien. Proin finibus arcu in sapien mollis dignissim. Aenean at elit sem. Nunc lacinia porttitor orci, id consequat dolor vestibulum ut. Quisque vehicula condimentum turpis. Etiam volutpat sem ac tortor aliquet, a finibus dolor rutrum. Praesent lobortis dui enim, at laoreet ipsum hendrerit vel. Nunc cursus dolor non arcu laoreet laoreet. Aliquam dictum odio non justo rutrum hendrerit. Fusce sodales iaculis vehicula. Curabitur imperdiet ipsum augue, vel tincidunt felis consequat nec. Sed nec augue vehicula, aliquam nunc nec, dapibus sem. Nullam nisi diam, lacinia in semper at, semper a purus. Nullam nunc eros, scelerisque eu auctor in, iaculis vitae libero. Sed a sapien ipsum. Nam tempor convallis nisi ac tempor. Nunc venenatis dictum eros, mattis pellentesque elit interdum vestibulum. Praesent et commodo eros, viverra vulputate dolor. Sed pharetra eleifend velit et feugiat. Nulla facilisi. Donec congue, velit et semper feugiat, tellus dolor bibendum dui, id ultricies enim urna a purus.</p>
    <ul>
        <li>Sed tristique interdum erat et vehicula. Proin magna elit, euismod vestibulum risus tempus, egestas cursus justo. Praesent vulputate velit quis bibendum ornare. Sed maximus quis enim eu lobortis. Aenean laoreet pellentesque orci, vitae tempor lacus vehicula eu. Etiam ullamcorper rhoncus ipsum at rhoncus. In mattis lacus et ipsum mattis, ac pulvinar sapien dictum. Ut at sem eu sapien porttitor luctus at vel felis.</li>
        <li>Praesent varius tincidunt lectus, non vulputate eros. Curabitur vitae leo non sapien ultrices interdum ut eget sapien. Vestibulum a fringilla risus. Etiam rutrum, odio vitae ultricies vulputate, nisl massa iaculis ligula, eget tincidunt velit elit ut mi. Pellentesque finibus scelerisque nulla. Duis mollis fermentum augue id fermentum. Donec sed bibendum elit. Integer interdum congue iaculis. Pellentesque tincidunt venenatis massa, id imperdiet nunc.</li>
        <li>Cras quis dictum lacus. Ut sodales, ipsum at fermentum consectetur, quam nulla tincidunt magna, vel pulvinar augue lacus vitae dolor. Curabitur aliquam aliquet enim, vitae iaculis felis tristique nec. Nullam sit amet sapien sapien. Nullam sed lectus felis. Vivamus at magna quis urna pulvinar iaculis. Etiam in commodo magna. Praesent accumsan dapibus lectus eu aliquam. Quisque pretium tellus vel dignissim facilisis. Sed eget lobortis massa, vitae bibendum justo. In arcu arcu, interdum sit amet felis eget, semper porta quam. Aenean iaculis tincidunt luctus. Aliquam erat volutpat. Mauris vulputate non orci sed tincidunt.</li>
    </ul>
    <p>Mauris ornare ullamcorper iaculis. Nunc ut convallis nunc. Phasellus tempus fermentum urna a malesuada. Mauris sed fringilla urna, vitae blandit dolor. Vestibulum at metus scelerisque, interdum elit sit amet, interdum justo. Mauris viverra dictum leo, vel tristique eros dignissim eget. Quisque vehicula mi eget enim cursus tincidunt. Nulla id dignissim odio. Maecenas posuere iaculis velit sit amet commodo. Nam et lorem eget sem placerat varius. Aenean eu ex mi. Cras erat nulla, imperdiet non porta vel, pulvinar eu arcu. Vestibulum rhoncus molestie convallis. Aenean commodo tristique orci, vel sodales odio aliquam vel. Nunc vestibulum, erat at porta accumsan, est dui varius nisl, ac commodo diam lorem id libero. Nam tincidunt consectetur odio ut finibus.</p>
    <p>Donec quis commodo purus, eget accumsan justo. Phasellus porta metus sit amet neque bibendum vestibulum. Aliquam tempor vestibulum lacus, non pellentesque nisl consectetur sit amet. Pellentesque ultricies id augue quis eleifend. Duis volutpat vehicula lorem sed cursus. Nulla facilisi. Donec nisl sapien, pellentesque et consectetur id, lacinia id nisl. Ut aliquet vestibulum mattis. Aenean ultrices id tellus non vulputate. Mauris feugiat lacus in urna ultricies laoreet. Proin imperdiet arcu at neque luctus, et egestas ante egestas.</p>
</section>
@endblock